### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by afavata** [Magento2Translations/language_it_it#1]
Hello

I have updated the language it_IT through the command 

composer update 

after that I have cleared and flushed the cache and run the command bin/magento setup upgrade which at the end pop up this error messagge:

 [Magento\Framework\Exception\LocalizedException]
  Field title can't be empty

can you please take a look at this urgently.... I'm currently stuck

Thanks

Alex

**Comment by MrGekko** [comment]
Do you have any more error information /console log?  What do you have in composer.json? Magento version? What other modules have updated?
